# Generated by Django 2.2.12 on 2020-05-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dersicerik', '0014_auto_20200530_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajdersmezun',
            name='dersicerik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajMezun', to='dersicerik.DersIcerikMezun'),
        ),
    ]
