# Generated by Django 2.2.12 on 2020-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200517_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='calismaDurumu',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='mezuniyetYili',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='telefonNumarasi',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='ogrenciNo',
            field=models.IntegerField(unique=True),
        ),
    ]
