# Generated by Django 2.2.12 on 2020-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200530_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='ogrenciNo',
            field=models.IntegerField(),
        ),
    ]
