# Generated by Django 2.2.12 on 2020-05-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200530_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='ogrenciNo',
        ),
    ]
