# Generated by Django 2.2.12 on 2020-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_ogrenci_ogrencino'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='ogrenciNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='telefonNumarasi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
