# Generated by Django 2.2.12 on 2020-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_mezun_mezuniyetyili'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='mezuniyetYili',
            field=models.DateField(blank=True, null=True),
        ),
    ]
