# Generated by Django 2.2.12 on 2020-05-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_mezun_mezuniyetyili'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='mezuniyetOrtalamasi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
