# Generated by Django 2.2.12 on 2020-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_mezun_mezuniyetortalamasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='mezuniyetOrtalamasi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
